default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: chonthuoc-api_development

  <<: *default
  database: chonthuoc-api_test

production:
  <<: *default
  database: chonthuoc-api_production
  username: chonthuoc-api
  password: <%= ENV['CHONTHUOC-API_DATABASE_PASSWORD'] %>
